version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo Build completed Successfully on `date`

artifacts:
  files:
    - target/*.jar   # ✅ FIXED
  discard-paths: yes
